version: '3'
services:
  db:
    image: postgres
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    command: npm run build
    volumes:
      - .:/poemist
  backend:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/poemist
    ports:
      - "7000:3000"
    depends_on:
      - db