version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: ls
    volumes:
      - .:/poemist
  backend:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/poemist
    ports:
      - "3000:3000"
    depends_on:
      - db
