default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['PSQL_PASSWORD'] %>
  host: <%= ENV['PSQL_HOST'] %>
  port: <%= ENV['PSQL_PORT'] %>
  pool: 5

development:
  <<: *default
  database: poemist_development

test:
  <<: *default
  database: poemist_test
